### ISSUE TITLE
How to *not* have a `particlesPath`?

### ISSUE THREAD

**Issue by mccoys** [ComputationalRadiationPhysics/openPMD-standard#143]
I am wondering how I could manage to *not* have a `particlesPath` in a file. It seems that the `checkOpenPMD_h5.py` tool is always looking for one, and searching it for all required attributes.

Is there a way to prevent that?

And what about having no `meshesPath` instead?

**Comment by ax3l** [comment]
Thank you for the question!

For now, just define it to an empty (or non-existing) folder.
Example: `meshesPath = "fields/"`, `particlesPath = "noParticles/"`

Readers looking for particles will check that path and see that the iteration contains indeed no particle species.

**Comment by ax3l** [comment]
ping @RemiLehe: what you asked today

I would suggest something like this in 1.0.1: Add a note at this point that each of the pathes might not exist and this needs to be handled as "no meshed (particles)" found.

We can decide if readers shall or must not issue a warning (but maybe a less important debug level such as info) in such a case. We could also say one should throw a warning but continue, if the path does not exist but throw not a warning if the path exists but no entries are found. But I guess no warning is the most reasonable way to handle this.

**Comment by ax3l** [comment]
discussion today:
even better: make the attributes optional instead of writing rubbish for 2.0 (but then the paths are required to exist if the attribute exists)

**Comment by ax3l** [comment]
@RemiLehe @C0nsultant I would suggest I fix the remaining `1.0.1` wording changes and make this an immediate follow-up `1.1.0`.

I would immediately relax both paths to be `optional` instead of allowing writing "something". This allows to implement it in yt, checker the viewer, etc. simply and together with the `1.0.X` implementations and makes it more clear what is happening.

I can also provide PRs for all three with the PR.

**Comment by anokfireball** [comment]
Admittedly, I still do not see how the proposed combination of required attribute and optional concrete path is the more sensible option for `1.0.X` (i.e. how this better represents the file in openPMD metadata than enforcing the path). If that is what it takes to not break a majority of the already existing output, this is probably inevitable.

Is `1.1.0` supposed to include the concept of `optional` attributes? If so, including the propsed change for it and `2.X.X` sounds reasonable enough to me. +1

**Comment by ax3l** [comment]
Sorry, I was too short. I overthought what I wrote above and would suggest the following.

I propose to introduce the following relaxation and of the two attributes `meshesPath` and `particlesPath`:

- relax the two attributes from `required` to `optional`
- in the case an attributes is not set, handle the file as if there are no meshes (particles)
- define that the path they describe MUST exist if the attributes are set (as most implemented it already like this in 1.0.0 and our validator does this also in a two-liner)

Version suggestion:

- change in `1.1.0`, so we have it even quicker than 2.0.0 (more features might come in)
- not change in `1.0.1` already since its more than a wording change but still easy to implement (100% backwards compatible for writers and easy to add for readers)

@RemiLehe @C0nsultant: would you agree with adding this to `1.1.0`?

I would prepare the PR for that after I did the minor `1.0.1` leftovers and will link there everything again before anything happens.
