### ISSUE TITLE
Units should not be forced to SI

### ISSUE THREAD

**Issue by mccoys** [ComputationalRadiationPhysics/openPMD-standard#155]
We [the Smilei developers] would like to propose a change that was discussed a little [somewhere else](https://github.com/SmileiPIC/Smilei/issues/3): **specifying units in SI could be optional**. In particular, this concerns the attributes `timeUnitSI` (in `basePath`), `gridUnitSI` (of each `mesh record`) and `unitSI` (of each `Record Component`).

We know that this possibility has found significant opposition here, but we would like to expose clearly the reasons, and a possible solution.

Why optional units?
----

From our perspective of PIC code developers and users, most of the simulations we run are scalable by some arbitrary factor. This is due to the Maxwell-Vlasov system of equations having a natural set of units: times, lengths, electromagnetic fields, densities and currents may be expressed in a normalized (unit-less) manner. They all depend on each other, but there is no absolute value of these quantities. In fact, the result of the simulation can be scaled using one arbitrary *number*, as long as each of the quantities above have been scaled in the correct way, with the correct exponent. Typically, in the case of the code Smilei, we have chosen this *number* to be in the dimensions of an angular frequency `Wr`. The simulation times are in units of `1 / Wr`, distances in units of `c / Wr`, densities in units of `ε0 m_e Wr^2 / e^2`, etc. The results of the simulations can be scaled by these factors. For instance, if you multiply all times by 2, then you also have to multiply distances by 2, and densities must be divided by 4.

This does not apply to PIC simulations with additional physics which require an absolute system of units (ionization, collisions, QED, etc.) but this case is trivial.

It turns out that many PIC codes disregard the fact that the PIC equations are naturally scalable by some factor, and impose some absolute units. In our opinion this is too restrictive. We don't mean PIC codes should change, but OpenPMD should respect the variety of codes that use meshes and particles in order to broaden its scope.

How to specify the simulation scaling?
----

Electromagnetic PIC codes are not the only ones that can be scaled. It is also the case for Vlasov codes, electrostatic [Poisson-Vlasov] codes, and, to some extend, hydro codes. Even though EM-PIC codes have only one scaling factor, in general, there may be more (e.g. two factors for Poisson-Vlasov codes).

We thus propose new optional attributes as follows:
* in `basePath`, a new `timeUnitScalings` attribute
* in each `mesh record`, a new `gridUnitScalings` attribute
* in each `Record Component`, a new `unitScalings` attribute

These new attributes should each be a list of floats. They must all have the same number of elements. Each element represent the power at which a scaling factor should be taken if a user wants to scale the simulation up or down.

Let's take an example. In a EM-PIC simulation, there is only one scaling factor (in Smilei, the `Wr` above). This means that each of the new attributes above should be a list of one float. In this case, `timeUnitScalings=[-1.]` because times scale as `1/Wr`, `gridUnitScalings=[-1.]` because distances scale as `1/Wr` and for a record component that represents a plasma density, `unitScalings=[2.]` because densities scale as `Wr^2`. In other cases, we may have several scaling factors, so that these lists of scalings may have more than one element.

**New rules**:
* Both `***unitSI` and `***unitScalings` are optional.
* The rule above implies that OpenPMD cannot enforce a comparison between units of data. It is up to the user to make sure they have understood the type of data they are handling.
* The absence of the `***Scalings` attributes means the data is not scalable by any factor. Alternately, it can be decided that an empty list should be defined instead.
* There may be both `***unitSI` and `***unitScalings` defined. The former being seen as the "default" scaling of the simulation, while the latter indicates that the simulation may be freely scaled.
* If any of the new attributes `timeUnitScalings`, `gridUnitScalings`, and `unitScalings` are defined, they must all have the same length.

Note that `Scalings` may not be the best wording for all attributes above. It can be confused with performance scalings (weak/strong scalings) in HPC computing. There could be a better word.

Doesn't this break OpenPMD fundamentals: making data comparable?
----

*If the data of one code cannot be represented in SI units, how are you supposed to compare it to another code?*
This has been one the most frequent arguments against having units optional. Let me explain why we disagree.

If one code provides simulation results in SI, and the other one normalized units, the user has to know what they want to compare and how the data should be modified in order to compare it. This is not the job of OpenPMD, in our opinion.  Many simulations are fundamentally scalable, and later comparison to other simulations must be dealt knowingly by the user. We believe that the new attributes above provide a complete manner to scale the data. OpenPMD clients will have to provide users with a way to introduce scaling factors. In fact, this somewhat ensures that users actually know what they are doing instead of randomly compare things.

Overall, we understand that this is a complex question that changes features in OpenPMD but we believe that it needs to be addressed to make OpenPMD widely used. We hope we have convinced you that the current standard has flaws with respect to units management.

**Comment by ax3l** [comment]
Thank you very much for opening an issue on the discussed points and the great description! We will answer you as soon as possible, just want to write properly and not in between two meetings (we had a major evaluation last week).

**Comment by DavidSagan** [comment]
> if one code provides simulation results in SI, and the other one normalized units, the user has to know what they want to compare and how the data should be modified in order to compare it. This is not the job of OpenPMD, in our opinion.

I agree. I don't think there will be a problem if the units would be made optional. One way to do this would be to have an optional boolian attribute in the root group called, say, `scalableUnits`. If `scalableUnits` is `False` (the default), units would **have** to be supplied. If `scalableUnits` is `True` then units would be optional.

**Comment by mccoys** [comment]
@DavidSagan I am not sure a boolean is the optimal idea. There could be an integer `numberScalingFactors` which represents obviously the number of scaling factors, or, in other words, the length of the lists defined above (`unitScalings`, etc.).

If `numberScalingFactors` equals 0, then units must be provided. Otherwise, they may or may not be defined.

On the other hand, one would argue that this attribute `numberScalingFactors` is redundant because it represent the length of lists that are already available. For this reason I suggest to avoid using another attribute like  `numberScalingFactors`  or `scalableUnits`.

**Comment by RemiLehe** [comment]
Sorry for my (very) delayed answer, and thanks for the detailed discussion of this issue. It is true that the issue of imposing SI units has also been criticized by other potential users of openPMD. Thus it would be great if this discussion could lead to a solution for these users, without disrupting the current ecosystem around openPMD.

As it is, however, my main concern is that the current proposal to make the SI units optional means that a number of **existing openPMD tools** that relied on it will not be able to do so anymore. In particular, I think that `yt` requires to know the conversion to SI units (but @C0nsultant could confirm this). And I think that the same holds for Visit (but @xxirii could say more on this).

Of course, one solution would be to accept that Visit and `yt` will still be able to read the files that contain `unitSI`, and they will not be able be to read those that don't. However, I would be strongly against this solution: if we make this kind of choice too many times (to accommodate the various requests that different users may have), then each code will have its own flavor of openPMD, which can be read and visualized by their own specialized tools, but not by the generic tools supported by openPMD. This goes against one of the aim of the standard, which is to centralize the efforts on the development of post-processing and visualization tools, so that the whole openPMD community
can benefit from them.

(*Note: to be fair, I have to admit that, even currently, some openPMD tools cannot read all types of openPMD files. For instance, `yt` cannot read openPMD files in quasi-cylindrical geometry. However, this is something that we want to avoid as much as possible, and that we are trying to fix whenever possible.*)

I hope other users can understand our position on this. If someone has a solution to this issue, I would definitely be open to it.

My personal inclination would be to still require the conversion to SI units in openPMD (as a default for a **particular value** of the scaling parameter `Wr`), and to allow the scaling parameters that @mccoys proposed, as an option (possibly in the ED-PIC extension).

**Comment by mccoys** [comment]
@RemiLehe Thank you for you detailed response.

I am not sure how OpenPMD interfaces with yt, but there is definitely a plugin that does the work in the case of Visit. Why not handle the missing ``unitsSI`` arguments in the plugin itself? It could set the scaling factors to 1 (in SI) by default.

**Comment by skuschel** [comment]
Thanks you very much for the detailed proposal. I really, really like the idea to add optional information about possible scalings of the simulation data. However, I do not see why this makes the `*UnitSI` attribute obsolete. Let me elaborate:

The `*UnitSI` attributes provide a **scaling factor** to convert the data to the corresponding SI Unit. This is essential to give the data a physical meaning and also to allow the comparison with experiments. The fact, that `yt` or `visit` require this information is just a manifestation of this idea. Therefore and for the reasons given by @RemiLehe I concur, to keep `*UnitSI` attributes mandatory.

However, this does not mean that the specific `*UnitSI` value is the **only** possible choice! They just provide **one** possible choice. If data can be scaled, there are various valid options. In general I think, that identifying possible options, how to scale the data, should be part of the post-processing and data evaluation: When you pick your plots, you also pick appropriate units.

Nonetheless the proposed scaling information may still be valuable to the human working with the data or even incorporated into some post-processing software. Therefore I support the `*UnitScalings` attribute, which could be used as proposed: to save the **scaling exponents** of the data (as shown in the example using `timeUnitScalings=[-1.]`).   
Consequently, I hereby propose to call the attribute `*UnitScalingExponents`.

In order to convert data to SI and apply possible scalings to the data, the **scaling factors** (`*UnitSI`) as well as the **scaling exponents** (`*UnitScalingExponents`) are required and I would keep them perfectly separated: The above example would therefore just be:  
`timeUnitSI = 1` 
`timeUnitScalingExponents=[-1]`
`gridUnitSI = c` (evaluated to a float, of course!)
`gridUnitScalingExponents=[-1]`
and within the density record:
`unitSI = ε0 m_e / e^2` (evaluated to a float, of course!)
`unitScalingExponents=[2]`
The `*UnitScalingExponents` would be an optional list and the absence of the attribute would be identical to an empty list. With this solution, any software/plugin can safely ignore the presence of the `*unitScalingExponents` attribute, which ensures downwards compatibility (and is identical to silently setting the scaling parameter to `1`).

**Comment by DavidSagan** [comment]
@skuschel:

> I do not see why this makes the *UnitSI* attribute obsolete.

No one is saying it is obsolete. The proposal here is to just make it optional.

> The *UnitSI* attributes provide a scaling factor to convert the data to the corresponding SI Unit. This is essential to give the data a physical meaning and also to allow the comparison with experiments. 

But the discussion here is what to do when the simulation uses normalized units which do not have a scaling factor.

> The fact, that yt or visit require this information is just a manifestation of this idea. 

Not true. If *UnitSI* were made optional then yt or visit could just use a default scaling factor of 1. The fact that this information is required now is just a reflection of the fact that the standard mandates *UnitSI* to be present.

> Nonetheless the proposed scaling information may still be valuable to the human working with the data

This is making things more complicated and I don't think the standard is best served by adding things that may be useful but that no one has said is actually useful. I would propose simply making the *UnitSI* attribute optional and yt or visit can use a default value of 1 so that data files without *UnitSI* can be visualized. This would overcome Remi's objection and, if later on, someone thinks that using *unitScalingExponents* would be useful, we can revisit the issue.

**Comment by skuschel** [comment]
@DavidSagan 
You are right, there are two issues here discussed at the same time:
1) making `*UnitsSI` optional.
2) adding the optional attribute `*UnitScalingExponents` or similar.

Regarding 1:
I apologize for my impression, that the `*UnitSI` may have been seen as obsolete. I agree with you, that it is not obsolete, which is why I cannot understand why it should be optional. No matter in what (normalized) units the simulation is carried out, there is always a factor to scale the data to SI. The inclusion of this factor (`*UnitsSI`) avoids confusion of the interpretation of the data. If there are multiple correct choices for such factors, the code has to pick one. I do not see why this is a problem and as soon as the simulation includes ionization or QED effects or whatever, there is only one choice left anyways.
@RemiLehe You said there have been other objections about the SI conversion. Can you please summarize what kind of criticism has been brought to your ears?

Regarding 2:
I personally like the inclusion of optional information in a standardized manner, which is why I would support the idea of adding `*UnitScalingExponents` or similar. However, I am happy with or without it.

Cheers!

**Comment by ax3l** [comment]
I read all your arguments and be assured first, that we are all aware about free parameters in systems of equations and that they are important to understand the physics they describe. But we also need to keep simple things simple and can not over-engineer the logic - simply for the sake of allowing easy implementations in readers. Please be aware that a relatively easy implementation of as much as possible of the openPMD (base) standard in *any reader* is a primary design goal of openPMD, contrary to implementing a special solution that only works for some viz/post-processing/... apps. An other primary constrain to make data portable is to *not* impose a unit system by a data writer, but only by the implementation a data reader provides.

Indeed, two things are mixed here: if first one needs an absolute unit scale and second if one needs to be able to express free parameters. Also, as Rémi mentioned already, standard and also its transitions need to be logic and simple, everything else creates a lot of work for the people that actually do the implementation in visualizations and breaking changes need to demonstrate they can be actually implemented (we will not shuffle the work down to the people maintaining the tools, frameworks & data frontends).

I invite you to follow a bit of the directions and design ideas we are facing here. First, I was inclined to say "sure, make unitSI *recommended* or even *optional*" but what do we get from that? Only a sub-set of readers (including e.g. other sims that will read in your data for e.g. particle transport after a PIC sim), that do not reference to an *absolute* unit scale (of any kind) will be able to read your data. We have to express even more sub-critera for readers so users understand when they are actually usable for their data and we scatter the data format. Basically we are close to where we started without a common standard, opening `h5py` on our files manually and shuffling axis scales by hand.

Let me catch up on the argument "the user needs to know what he/she does" - I support that to some extend but allow me to introduce *how* we thought of this when designing `unitSI`.

If a user (or app developer) knows that a certain parameter is free, let's say the whole simulation scales with a plasma frequency, sqrt of a density, whatever, this is fine. One can still arbitrarily chose a reference to fix the absolute scale ("fixation"), *one just needs to express that one did that* in both a *human readable* (currently via a comment) **and/or even better** a *machine readable* way (the issue we are discussing here).

Even with such a fixation, a reader can implement a unit system *hiding the fixation* and just convert everything *with the help of the user* relative to a domain-specific, scalable expression again and it's can be done fully manual after read of an absolute unit system or *assisted* in very simple logic. We even outlined a draft for it in https://github.com/openPMD/openPMD-viewer/issues/64. (Btw, PRs welcome!) The only thing we did not nail down in the 1.X standard for it are what I would call *comfort functionality* (automation of that workflow via *machine readability*), namely to express *what are the arbitrarily chosen absolute references* because otherwise the user needs to say those fixations during data read to hide it again. This automation is something that we can add now.

So that said, I think the easiest way could be to keep an absolute unit reference and `unitSI` *required* in the *format*. But do not despair yet! Note that this is not necessarily something a user will even see (but a writer and reader developer). If you think that is in the first step arbitrary you are right, but allow me to quote Hermann Weyl:

> The introduction of numbers [...] is an act of violence.

which, simply put, was already an act of violence as we put numbers and discretizations in our governing set of equations. The trick now is how to *unravel* this again without the user realizing (aka interfacing with) it. Note: with user I refer to someone *using* an app and post-processing tool, not someone that writes the app or the data reader.

Now the important *addition* would be to machine-readable express what the scaling is, very much as you converge to above. Probably this can be as simple as *storing the fixation parameter* that was arbitrarily chosen in order to fix for an absolute unit system:
- absolute value that was taken for the fixation
- exponents of its unitDimension

What that, one could even add an auto-converter for e.g. a plasma-units in post-processing (everything in powers of m_e, omega_pe, c, q_e, ...) in https://github.com/openPMD/openPMD-viewer/issues/64 without any question to the user for a given file.

The implementation in **writers** would be simple with two new, optional base attributes. Data **readers** can either just take the absolute system that was already fixed and leave the further conversion fully to the user *or* can chose to implement arbitrary non-absolute and even domain-specific unit systems as linked above (which is nice and comforting and can reflect scalability again). Not all data readers can support the second case but one will *always* get data *in* with case one, even in *a* correct representation. One can further convert it with manual user-work if needed if case two is not present (and we know that there are many frameworks that do not support it).

A last note for now: I think we should still be aware that there can be *more than one* additional degree of freedom in some cases, so likely a *single* parameter such as reference the cases we are thinking right now as a chosen plasma frequency / density / wavelength / ... parameter. So *one* fixation parameter might still not cut all cases and we might just need to allow a list of fixation parameters here.

**Comment by ax3l** [comment]
Maybe we can just rename:

- `unitSI` -> `unitScaling` (*optional*, default: `1.0`)

Introduce a string attribute alongside each record (or for the sake of simplicity, for each openPMD file series):

- `unitSystem` (*required*, allowed values: `SI`, ~~`CGS`~~ (later), `other:<nonStandardUserDefined>`)

then define a few unit systems (labels of base units, relation to `unitDimension`, conversion to known unit systems such as CGS). If `other:*` is chosen require `unitScaling == 1.0` & rely on labels #149 for ranges/values (axes/colorbars) but loose convertibility until a user manually post-processes the attributes to set a known unit-system and correct `unitScaling` attributes.

`unitDimension` just says with the seven base quantities we defined so far and expresses *dimensionality*.

Could it really be that simple? I think I am missing something.

**Comment by mccoys** [comment]
@ax3l 

It seems like a good idea, at least from my point of view. There would be a few minor points to be addressed though. For instance, what would be the use of specifying ``<nonStandardUserDefined>``? Where would it be employed? If labels can give symbols to correctly express the units in plots, that should be sufficient. Also, why require ``unitScaling == 1.0`` ? That could be another value, or the default ``1.0`` if not indicated.

Now, there is one (possibly important) issue: this does not solve the problem of making data from different codes comparable. If one code outputs normalized data and another one data in SI units, then the standard does not offer a way to scale the data in a simple manner. The user would have to manually scale each record without explicit help on how to scale that data in order to make both outputs in the same unit system. I simply want to point out that this information would not be contained in the file itself.

**Comment by ax3l** [comment]
> what would be the use of specifying `<nonStandardUserDefined>`? 

The main point is that it is prefixed with `other:` and a user could just specify anything after it. It is not relevant for the standard but might have a meaning for a domain/app-specific post-processing of a user.

We can also just set `other`, since the base standard can not help with conversions in such a case anyway, but allowing more information might help you at some point.

> Also, why require unitScaling == 1.0 ? That could be another value, or the default 1.0 if not indicated.

Yes, definitely - I just wanted to avoid introducing labels in #149 for both units *before* and *after* scaling. In #149 we will define a purely informational label *before* scaling.

Anyway, for axis/colorbar labels one can also just show *dimensions* instead of units with an `other:` unit system (from `unitDimensions`). Based on the `other:` `unitSytem` and `untiDimensions` a *domain-specific* post-processing that understands `other:smilei` can also map *dimensions* to plasma-frequencies, etc. again.

> this does not solve the problem of making data from different codes comparable
> [...]
> I simply want to point out that this information would not be contained in the file itself.

yes, and that's the point, we don't see how we can make two unit systems without an absolute reference scale reliably/generally comparable atm. One either needs additional info in the absolute system or a fixation of parameters in the relative system.

One can do that if one knowns what `other:` system is with manual intervention for very specific applications but not in general due to the lack of a reference. To quote the issue description:

> It is up to the user to make sure they have understood the type of data they are handling.

Of course, one can provide that information in domain-specific post-processing with any logic one likes.

**Comment by RemiLehe** [comment]
@mccoys To answer your question a bit further, I think that there are (as mentioned before) two orthogonal aspects:

- **Stop forcing codes to provide a conversion to SI**: As I understand it, this is very important for codes (like Smilei) that define all quantities with respect to the plasma density. @ax3l's above proposal is one way to solve this issue.

- **Indicate how quantities scale with respect with a given scaling parameter, so that codes that output results in SI units could be compared with codes that output results in normalized units**. As I understand it, this is somewhat less important for codes like Smilei (it would nice to have it, but maybe it is not strictly needed for these codes to fully adopt the openPMD standard; is that correct?). It seems that @mccoys's proposal to introduce `unitScalings` parameters attempts to address this issue.

In my opinion, the first aspect of this discussion could be addressed and implemented in openPMD rather soon. However, I am not sure that we have a clear solution for the second solution (especially for how users would use this: see below). Therefore I am wondering if we could (at least for now) drop the discussion of that second aspect. @mccoys : Would that be fine with you?

Here is why I think that the current solution (i.e. `unitScalings`) is not sufficient for comparing codes that output their data in SI and normalized units: 

Imagine that a user (who knows nothing about the internals of Smilei, and in particular its units system) wants to compare simulation results from, say, PIConGPU (which provides a `unitSI` coefficient) and Smilei (which does not, but would, hypothetically, provide the `unitScalings`). Even if that users knows how the Smilei results scale (thanks to the `unitScalings` coefficients), he would still miss a key information: the value of the scaling factor (Smilei's `Wr`) that he needs to apply to in order to match the results from both codes. Of course, Smilei could store this value in the openPMD file. But then, this is precisely the kind of loss of generality that Smilei would like to avoid. Also, if we store `Wr`, we may as well provide `unitSI` instead.

My personal opinion would be to allow Smilei and other codes to stop providing `unitSI` (e.g. using what @ax3l proposed), but then the data is not meant to be compared with a simulation in SI units. If the data is meant to be compared with a simulation in SI units, then Smilei would have to provide the `unitSI` coefficient.

**Comment by mccoys** [comment]
@RemiLehe I agree with everything you said:

* Stop forcing SI units is mandatory for the data to be consistent in some codes.
* Giving a way to scale the data is not mandatory; only convenient. This can be a discussion for future changes. However, if any comparison to another code requires the whole data to be recomputed, it seems a little awkward and a lot of time lost. Having a way to scale the data *a posteriori* would be a good addition.

**Comment by ax3l** [comment]
so instead of renaming `unitScaling` we agree that just making `unitSI` recommended will mean: we don't know the conversion to SI. So we don't need `unitSystem` in that case. Works for me.

**Comment by ax3l** [comment]
We would propose to simply make the `unitSI` from *required* to *recommended* for 2.0.0.

Just to be open about this, contrary to making it fully *optional* this would mean that due to the limited portability of such a records (or full file), the [openPMD-validator](https://github.com/openPMD/openPMD-validator/) will throw a warning.

This is no problem for your data though, since general openPMD readers will still read the data (and probably put dimensions instead of labels on an axis)! As the standard states in section on *Implementations*:
> warnings and further constrains:
> if the provided validator/checker scripts throw warnings (and the file does not violate the standard due to missing coverage of a certain critera in the scripts) the reader must be able to read the file

Would that be ok with you @mccoys ?

**Comment by RemiLehe** [comment]
@mccoys As Axel suggested the idea is that `unitSI` would not be required anymore. But we will probably add some language in the standard, saying that not specifying SI units should only be done when it is indeed fundamentally impossible to convert to SI units (e.g. when a Smilei user did not provide a reference density). 

Whenever the data is convertible to SI units (e.g. when using ionzation or QED), I think that the SI units coefficients should be written in the openPMD file, and a viewer/plotter should show the data in SI units instead of normalized units, so as to avoid any confusing. Would you agree with this?

**Comment by ax3l** [comment]
> and a viewer/plotter should show the data in SI units instead of normalized units, so as to avoid any confusing [...]

You probably talk about the reference impl in `openPMD-viewer`, where I agree it makes sense.
If we don't have an absolute unit (aka no `unitSI`), we should just plot the power of the dimensions (from `unitDimension`, e.g. [`[L^1 T^-1]`](https://en.wikipedia.org/wiki/SI_base_unit)) instead of a unit, e.g. in different brackets.

For domain-specific viewers/plotters, it is up to the implementer and can be also a different default or even a user-chosen system if needed. A domain-specific plotter can also look up and guess that `[T^-1]` might be a plasma frequency. That's easily doable with e.g. pint but requires domain expert knowledge (the openPMD *base* standard is not bound to a certain science domain). Of course, e.g. the `ED-PIC` extension or a general `Plasma` extension could define such things.

But I am getting off-topic, these are separate issues we can open and work on if someone needs those. For now, let's make `unitSi` *recommended* instead of *required* (see implications and difference to *optional* above).

**Comment by mccoys** [comment]
Sorry I did not realize questions where asked to me. I agree that the *recommended* ``unitSI`` fixes the issue with respect to Smilei. If that is acceptable for the philosophy of this standard, then I support this change.

**Comment by ax3l** [comment]
Wohow, implemented in #190.
Thank you to all who contributed! :guitar:  :rocket: :sparkles:
