### ISSUE TITLE
Remove meshesPath and particlesPath attributes

### ISSUE THREAD

**Issue by DavidSagan** [ComputationalRadiationPhysics/openPMD-standard#159]
Removing `meshesPath` and `particlesPath` attributes and instead using standard group names of `meshes` and `particles` will simplify both the standard and the make files easier to understand for a human looking directly at the data.

**Comment by ax3l** [comment]
The current proposal in #143 just proposes to:
- make both optional
- if one is set, it means there must be a valid path behind it, otherwise it means there are no meshes/particles to interpret

Will that work for you as well?

The idea is to allow people that have a structure such as
- `/something/<it>/fields` or
- `/something/<it>/meshes`

to keep it without changing fundamental path names.

If nobody insists, we can also remove that flexibility as you propose, but the idea is rather to become more flexible over time (e.g. allow to change the `basePath` as well) instead of more restricted.

**Comment by DavidSagan** [comment]
OK making it optional would work.

**Comment by ax3l** [comment]
I think #143 / #171 provided the solution for it :)
