### ISSUE TITLE
Proposed: particleState record

### ISSUE THREAD

**Issue by DavidSagan** [ComputationalRadiationPhysics/openPMD-standard#200]
Some particles in a bunch may get lost (EG hit the vacuum chamber wall) and it may be desirable to record their "final" positions along with the rest of the particles. I therefore propose an optional **particleStatus** record in the Particle Root Group. I'm thinking this could be an integer with 0 indicating the particle is "alive" and anything else means "dead". 

For Bmad, at least, it is useful to be able to distinguish different ways in which a particle can die (for example, hit the upper part of the vacuum pipe verses got reflected backwards in a RF cavity). Unfortunately I cannot think of a "universal" way to express this so just leaving it up to the program writing the file exactly what a non-zero value means in terms of mode of death I think is an acceptable solution.

**Comment by DavidSagan** [comment]
I would make ParticleState optional.

**Comment by ax3l** [comment]
Thanks for the proposal!
We have a similar case in PIConGPU on which we record particle leaving the simulation domain for virtual detectors.

Wouldn't you just add such particles in a special ("left-the-box") particle species (group)? Practically, that's how we do it. Additionally, one could add a scalar particle record remembering the time when a specific particle in such a particle was moved to the "dead"/"lost" species.

So there might be two relevant particle records here: *current state* (left box / normal / absorbed / ...) and *when* the last state change happened temporally. In the example I described in the paragraph above, I would then store the first usually as constant record for the whole "special" particle species group and keep the second (time when this happend) variable per particle as a regular record.

**Comment by DavidSagan** [comment]
@ax3l 
>Wouldn't you just add such particles in a special ("left-the-box") particle species (group)?

This is possible but if there are multiple bunches it simplifies the bookkeeping to not create separate groups.

>So there might be two relevant particle records here: current state (left box / normal / absorbed / ...) and when the last state change happened temporally. In the example I described in the paragraph above, I would then store the first usually as constant record for the whole "special" particle species group and keep the second (time when this happend) variable per particle as a regular record.

The absolute time is already a per particle record.

**Comment by ax3l** [comment]
Reminds me of: #42

**Comment by ax3l** [comment]
Today's meeting result: let's put it in `EXT:BeamPhysics` first and then check if we also take it for `EXT:ED-PIC` et al. :)

**Comment by skuschel** [comment]
I do not understand what information we gain by defining a particle state. The list of possible particle states ("left the box", "annihalated", "recombined with atom A", "recombined with atom B", "left the box on top",...) is a open list. Therefore I do not see a benefit in standardizing it and everything else is exactly what the comments section is for.
Also I do not understand, why less groups simplify bookkeeping. Having all particles sorted into groups is easy and disabled particles can be skipped in one step instead of checking every particle on its own. I think the standard supports disabled particles already, so I really dont understand why there should be the same functionality twice. This would just lead to multiple ways of doing one thing, making things unnecessary complicated.

**Comment by DavidSagan** [comment]
> I do not understand what information we gain by defining a particle state. The list of possible particle states ("left the box", "annihalated", "recombined with atom A", "recombined with atom B", "left the box on top",...) is a open list. 

Correct. Therefore there is no proposal to standardize this list. The only thing that is proposed is to standardize the name **particleStatus**.

> Therefore I do not see a benefit in standardizing it and everything else is exactly what the comments section is for.

Carful. "it" in this case is the name **particleStatus** not the list. Here is an example of how this could be useful: Program A saves coordinates of both living and dead particles. Program B reads in this file and, since particleStatus is part of the standard, program B can tell which particles it can ignore if it only wants to consider the living particles.

> Also I do not understand, why less groups simplify bookkeeping. Having all particles sorted into groups is easy and disabled particles can be skipped in one step instead of checking every particle on its own. 

Yes this will be simpler in **some** cases and the standard will support that. In other cases, where there are multiple bunches, it can be more convenient to keep all the particles, alive and dead, in one group.

> I think the standard supports disabled particles already, so I really dont understand why there should be the same functionality twice. This would just lead to multiple ways of doing one thing, making things unnecessary complicated.

There are always tradeoffs here. Actually at this point the standard does not have anything about marking a particle state so this is not a multiple way of doing things.

**Comment by skuschel** [comment]
> > I do not understand what information we gain by defining a particle state. The list of possible particle states ("left the box", "annihalated", "recombined with atom A", "recombined with atom B", "left the box on top",...) is a open list.
> 
> Correct. Therefore there is no proposal to standardize this list. The only thing that is proposed is to standardize the name **particleStatus**.

Consequently a `particleStatus==5` can mean the same as another codes `particleStatus==7 or particleStatus==9`. IMHO I totally prefer comments over this. They would be at least human readable.
> 
> > Therefore I do not see a benefit in standardizing it and everything else is exactly what the comments section is for.
> 
> Carful. "it" in this case is the name **particleStatus** not the list. Here is an example of how this could be useful: Program A saves coordinates of both living and dead particles. Program B reads in this file and, since particleStatus is part of the standard, program B can tell which particles it can ignore if it only wants to consider the living particles.
> 
> > Also I do not understand, why less groups simplify bookkeeping. Having all particles sorted into groups is easy and disabled particles can be skipped in one step instead of checking every particle on its own.
> 
> Yes this will be simpler in **some** cases and the standard will support that. In other cases, where there are multiple bunches, it can be more convenient to keep all the particles, alive and dead, in one group.

I tend to disagree. It is not about convenience here, otherwise we would not need OpenPMD, because every code would just write data as it is "convenient". It is about having standard information in a standard format. Furthermore, whats wrong with `electons_bunchX_alive` and `electrons_bunchX_deadforreasonY`? Many codes already do this if the particle left the box. Why reinvent the wheel? Having a few 100 particle groups is totally legit, it is not "inconvenient" (whatever that is supposed to mean), nor does it imply mayor performance degradation.
> 
> > I think the standard supports disabled particles already, so I really dont understand why there should be the same functionality twice. This would just lead to multiple ways of doing one thing, making things unnecessary complicated.
> 
> There are always tradeoffs here. Actually at this point the standard does not have anything about marking a particle state so this is not a multiple way of doing things.

I just do not see the necessity  as there is no list of possible particle states. Its just another field which contains number and the meanings of the numbers are not clear. Therefore the number can safely be written in the comments, because you need a human for its interpretation. You cannot automate it. 

Besides: If all other particleStates remain undefined, lets at least define `particleState==0`: What exactly is an "alive" particle? A particle which takes part in all simulation steps? Certainly! What about a particle which takes part in charge calculations, but does not move (fixed ion background)? Or the opposite: A particle which moves, but does not take part in current deposition (tracer particles)? Are tracers "half-alive", because some steps during one iteration are skipped? What about particles which do move and deposit currents, but which are excluded from QED or collision calculations? 

If you feel that there is the need for another "general purpose per particle property", then there should be reason, why groups cannot handle it. A good reason for that may be that the particleState is a vector or a float.

I think we need to be careful, that introducing too many options of how information could possibly be provided does not lead to too many different "flavours" of OpenPMD. That would counteract the first idea of the standard: To be able to automate the information flow unambiguously and exchange data **with minimal effort** [see README]

**Comment by DavidSagan** [comment]
> Consequently a particleStatus==5 can mean the same as another codes particleStatus==7 or particleStatus==9. IMHO I totally prefer comments over this. They would be at least human readable.

Provision for a translation table could be made to make things human understandable.

> I tend to disagree. It is not about convenience here, otherwise we would not need OpenPMD, because every code would just write data as it is "convenient". It is about having standard information in a standard format. Furthermore, whats wrong with electons_bunchX_alive and electrons_bunchX_deadforreasonY? Many codes already do this if the particle left the box. Why reinvent the wheel? Having a few 100 particle groups is totally legit, it is not "inconvenient" (whatever that is supposed to mean), nor does it imply mayor performance degradation.

There are several things to consider here. Convenience is one factor but not the only one. The bottom line is will this be useful. Maybe having a few 100 particle groups with different states would be fine for your purposes but for for simulations I run this would not be. 

> I just do not see the necessity as there is no list of possible particle states. Its just another field which contains number and the meanings of the numbers are not clear. Therefore the number can safely be written in the comments, because you need a human for its interpretation. You cannot automate it.

Not true. Bmad based programs can use **particleStatus** to transmit information without human intervention.

> Besides: If all other particleStates remain undefined, lets at least define particleState==0: What exactly is an "alive" particle? A particle which takes part in all simulation steps? Certainly! What about a particle which takes part in charge calculations, but does not move (fixed ion background)? Or the opposite: A particle which moves, but does not take part in current deposition (tracer particles)? Are tracers "half-alive", because some steps during one iteration are skipped? What about particles which do move and deposit currents, but which are excluded from QED or collision calculations?

This is a valid point. But consider this: For simulations of accelerators, most of the time, "dead" means hit the vacuum chamber wall and "alive" means the particle is still moving and that is the only information that is needed. So for many simulations, particleStates will be useful as is.

>If you feel that there is the need for another "general purpose per particle property", then there should be reason, why groups cannot handle it. 

Yes I feel there is need for this. And right now the standard does not have anything that can take its place. The standard has no convention for designating dead particle groups.

> I think we need to be careful, that introducing too many options of how information could possibly be provided does not lead to too many different "flavours" of OpenPMD. That would counteract the first idea of the standard: To be able to automate the information flow unambiguously and exchange data with minimal effort [see README]

Again, currently there is no other option. By the way, after talking to Remi and Axel, the plan is to put particleState into the beam physics extension and not the base standard. So if you do not plan to use the beam physics extension you do not have to bother about this.

**Comment by skuschel** [comment]
In fact, there **is** another option, which is particle groups. Anyways, if you guys are all convinced, that this is not only useful, but **necessary to represent information, that cannot be represented by the current version**, keep going. Just for the record: I strongly vote against this change as it does not simplify the exchange of information between different programs (meaning programs, which have been developed independently) or visualization tools.

**Comment by ax3l** [comment]
I think indeed taking numbers & translation tables is not ideal but we want to make it a record (constant or not) putting strings is not great, because each entry has a different length if non-constant.

If we, on the other hand, don't want to label individual particles but whole particle species (groups) for now, a comment, reserved new a string attribute (instead of a magic number) or a group-label #163 would do as well. @DavidSagan do you need it for particles inside a species group or for full species groups for now? If the latter, I would recommend an optional species group string attribute in `EXT:BeamPhysics`. If you add it, define as many states as you are aware of and an `other:freeText` option. Otherwise it's indeed of little help to reserve the keyword even in an extension as @skuschel mentions correctly.

(One can also add program-specific meta data on top of openPMD. We do so as well in some cases that are not worth standardizing because they are e.g. in-program- or checkpoint-specific.)

**Comment by DavidSagan** [comment]
@ax3l I need it particle-by-particle and not on a per-group basis so a species group string is not helpful. My experience is that by far most simulations simply care about the particle being "alive" versus "not alive" so using an integer will generally not be problematic.

**Comment by skuschel** [comment]
I could not stop thinking about it and in my perspective, there are two things which need to be clarified:
1) Why can the information not be provided within the possibilities of the current standard? I.e. What is the argument, that this is really needed on a per-particle basis and and not on per-particle group?
2) How does the change enhance interoperability with other simulations? Of course meaning other simulations which have been developed independently. If this is specific to Bmad based programs (as mentioned earlier), other software might not be able understand the meaning correctly. I am wondering if you could please add some specific examples from Bmad and other software packages? What states do they distinguish, why and how is it implemented? That might be very much helpful. Thank you!

**Comment by DavidSagan** [comment]
@skuschel 

1. There currently is nothing in the standard saying how to specify a "dead" particle group. If you believe otherwise please provide an example or pointer to where in the standard this is discussed.

2. As I mentioned earlier, my experience is that by far most simulations simply care about the particle being "alive" versus "not alive" and the proposed "particleState" standard is unambiguous on this. Thus this will be useful outside of Bmad. In Bmad the particle states are:
```
alive
lost_neg_x_aperture
lost_pos_x_apertue
lost_neg_y_aperture
lost_pz_aperture
lost     !  Catchall used if not one of the above lost states is appropriate 
```

**Comment by ChristopherMayes** [comment]
I am in favor of adding the per-particle particleStatus(integer), with a list of common statuses enumerated in the standard. Particle status is used by many codes, and sometimes this list can be long. See, for example, the Astra manual: 
http://www.desy.de/~mpyflo/Astra_manual/Astra-Manual_V3.2.pdf

Alive (track) and dead (don't track) could be standardized, with more added as the common needs are identified.

**Comment by DavidSagan** [comment]
See page 3 of the Astra manual. One thought would be to have a second per-particle record called particleType which could be used to sort out passive particles from ref particles from probe particles, etc. At this point, since I don't understand the details, I'm not advocating this but it is something to think about.

**Comment by DavidSagan** [comment]
Implemented in Beam Physics extension.
